api:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 40s
  write_timeout: 20s
  read_head_timeout: 50s
  secret_key: secret-admin-key
log_level: "debug"
debug: true
image:
  upload_dir: "./upload"
  model_dir: "./models"
