// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

// CreateEmployeeRequest defines model for CreateEmployeeRequest.
type CreateEmployeeRequest struct {
	Meta    Meta   `json:"meta"`
	Name    string `json:"name"`
	PhotoID int64  `json:"photo_id"`
}

// CreateEmployeeResponse defines model for CreateEmployeeResponse.
type CreateEmployeeResponse struct {
	ID      int64  `json:"id"`
	Meta    Meta   `json:"meta"`
	Name    string `json:"name"`
	PhotoID int64  `json:"photo_id"`
}

// DeleteEmployeeResponse defines model for DeleteEmployeeResponse.
type DeleteEmployeeResponse struct {
	Message string `json:"message"`
}

// Employee defines model for Employee.
type Employee struct {
	ID      int64  `json:"id"`
	Meta    Meta   `json:"meta"`
	Name    string `json:"name"`
	PhotoID int64  `json:"photo_id"`
}

// EmployeeBase defines model for EmployeeBase.
type EmployeeBase struct {
	Meta    Meta   `json:"meta"`
	Name    string `json:"name"`
	PhotoID int64  `json:"photo_id"`
}

// Error defines model for Error.
type Error struct {
	Error *string `json:"error,omitempty"`
}

// GetEmployeeResponse defines model for GetEmployeeResponse.
type GetEmployeeResponse struct {
	ID      int64  `json:"id"`
	Meta    Meta   `json:"meta"`
	Name    string `json:"name"`
	PhotoID int64  `json:"photo_id"`
}

// GetImageDescriptionResponse defines model for GetImageDescriptionResponse.
type GetImageDescriptionResponse struct {
	ID   int64  `json:"id"`
	Path string `json:"path"`
}

// Image defines model for Image.
type Image struct {
	ID   int64  `json:"id"`
	Path string `json:"path"`
}

// ListEmployeesResponse defines model for ListEmployeesResponse.
type ListEmployeesResponse = []Employee

// Meta defines model for Meta.
type Meta struct {
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RecognizeEmployeeResponse defines model for RecognizeEmployeeResponse.
type RecognizeEmployeeResponse struct {
	ID      int64  `json:"id"`
	Meta    Meta   `json:"meta"`
	Name    string `json:"name"`
	PhotoID int64  `json:"photo_id"`
}

// UpdateEmployeeRequest defines model for UpdateEmployeeRequest.
type UpdateEmployeeRequest struct {
	ID      int64  `json:"id"`
	Meta    Meta   `json:"meta"`
	Name    string `json:"name"`
	PhotoID int64  `json:"photo_id"`
}

// UpdateEmployeeResponse defines model for UpdateEmployeeResponse.
type UpdateEmployeeResponse struct {
	ID      int64  `json:"id"`
	Meta    Meta   `json:"meta"`
	Name    string `json:"name"`
	PhotoID int64  `json:"photo_id"`
}

// UploadImageResponse defines model for UploadImageResponse.
type UploadImageResponse struct {
	ID   int64  `json:"id"`
	Path string `json:"path"`
}

// GetImageDescriptionParams defines parameters for GetImageDescription.
type GetImageDescriptionParams struct {
	// Image ID
	ID uint64 `form:"id" json:"id"`
}

// DownloadImageParams defines parameters for DownloadImage.
type DownloadImageParams struct {
	// Image ID
	ID uint64 `form:"id" json:"id"`
}

// CreateEmployeeJSONBody defines parameters for CreateEmployee.
type CreateEmployeeJSONBody = CreateEmployeeRequest

// DeleteEmployeeParams defines parameters for DeleteEmployee.
type DeleteEmployeeParams struct {
	// Employee ID
	ID uint64 `form:"id" json:"id"`
}

// GetEmployeeParams defines parameters for GetEmployee.
type GetEmployeeParams struct {
	// Employee ID
	ID uint64 `form:"id" json:"id"`
}

// UpdateEmployeeJSONBody defines parameters for UpdateEmployee.
type UpdateEmployeeJSONBody = UpdateEmployeeRequest

// CreateEmployeeJSONRequestBody defines body for CreateEmployee for application/json ContentType.
type CreateEmployeeJSONRequestBody = CreateEmployeeJSONBody

// UpdateEmployeeJSONRequestBody defines body for UpdateEmployee for application/json ContentType.
type UpdateEmployeeJSONRequestBody = UpdateEmployeeJSONBody

// Getter for additional properties for Meta. Returns the specified
// element and whether it was found
func (a Meta) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Meta
func (a *Meta) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Meta to handle AdditionalProperties
func (a *Meta) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Meta to handle AdditionalProperties
func (a Meta) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Upload image on server
	// (POST /image/upload)
	UploadImage(c *gin.Context)
	// Download image from server
	// (GET /images/data)
	GetImageDescription(c *gin.Context, params GetImageDescriptionParams)
	// Download image from server
	// (GET /images/file)
	DownloadImage(c *gin.Context, params DownloadImageParams)
	// Create new employee
	// (POST /staff/add)
	CreateEmployee(c *gin.Context)
	// Get all staff
	// (GET /staff/all)
	ListEmployees(c *gin.Context)
	// Delete employee
	// (DELETE /staff/delete)
	DeleteEmployee(c *gin.Context, params DeleteEmployeeParams)
	// Get employee
	// (GET /staff/get)
	GetEmployee(c *gin.Context, params GetEmployeeParams)
	// Recognize employee
	// (POST /staff/recognize)
	RecognizeEmployee(c *gin.Context)
	// Update employee
	// (PUT /staff/update)
	UpdateEmployee(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
}

type MiddlewareFunc func(c *gin.Context)

// UploadImage operation middleware
func (siw *ServerInterfaceWrapper) UploadImage(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.UploadImage(c)
}

// GetImageDescription operation middleware
func (siw *ServerInterfaceWrapper) GetImageDescription(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetImageDescriptionParams

	// ------------- Required query parameter "id" -------------
	if paramValue := c.Query("id"); paramValue != "" {

	} else {
		c.JSON(http.StatusBadRequest, gin.H{"msg": "Query argument id is required, but not found"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", c.Request.URL.Query(), &params.ID)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter id: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetImageDescription(c, params)
}

// DownloadImage operation middleware
func (siw *ServerInterfaceWrapper) DownloadImage(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params DownloadImageParams

	// ------------- Required query parameter "id" -------------
	if paramValue := c.Query("id"); paramValue != "" {

	} else {
		c.JSON(http.StatusBadRequest, gin.H{"msg": "Query argument id is required, but not found"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", c.Request.URL.Query(), &params.ID)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter id: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DownloadImage(c, params)
}

// CreateEmployee operation middleware
func (siw *ServerInterfaceWrapper) CreateEmployee(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.CreateEmployee(c)
}

// ListEmployees operation middleware
func (siw *ServerInterfaceWrapper) ListEmployees(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.ListEmployees(c)
}

// DeleteEmployee operation middleware
func (siw *ServerInterfaceWrapper) DeleteEmployee(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteEmployeeParams

	// ------------- Required query parameter "id" -------------
	if paramValue := c.Query("id"); paramValue != "" {

	} else {
		c.JSON(http.StatusBadRequest, gin.H{"msg": "Query argument id is required, but not found"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", c.Request.URL.Query(), &params.ID)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter id: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DeleteEmployee(c, params)
}

// GetEmployee operation middleware
func (siw *ServerInterfaceWrapper) GetEmployee(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEmployeeParams

	// ------------- Required query parameter "id" -------------
	if paramValue := c.Query("id"); paramValue != "" {

	} else {
		c.JSON(http.StatusBadRequest, gin.H{"msg": "Query argument id is required, but not found"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", c.Request.URL.Query(), &params.ID)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter id: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetEmployee(c, params)
}

// RecognizeEmployee operation middleware
func (siw *ServerInterfaceWrapper) RecognizeEmployee(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.RecognizeEmployee(c)
}

// UpdateEmployee operation middleware
func (siw *ServerInterfaceWrapper) UpdateEmployee(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.UpdateEmployee(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router *gin.Engine, si ServerInterface) *gin.Engine {
	return RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router *gin.Engine, si ServerInterface, options GinServerOptions) *gin.Engine {
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
	}

	router.POST(options.BaseURL+"/image/upload", wrapper.UploadImage)

	router.GET(options.BaseURL+"/images/data", wrapper.GetImageDescription)

	router.GET(options.BaseURL+"/images/file", wrapper.DownloadImage)

	router.POST(options.BaseURL+"/staff/add", wrapper.CreateEmployee)

	router.GET(options.BaseURL+"/staff/all", wrapper.ListEmployees)

	router.DELETE(options.BaseURL+"/staff/delete", wrapper.DeleteEmployee)

	router.GET(options.BaseURL+"/staff/get", wrapper.GetEmployee)

	router.POST(options.BaseURL+"/staff/recognize", wrapper.RecognizeEmployee)

	router.PUT(options.BaseURL+"/staff/update", wrapper.UpdateEmployee)

	return router
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RYW2/bthf/KsT5/x82QInT3R70tGXeAgMrGrTZU2EMtHRks+NFIalmXqDvPhzS8iWi",
	"HDd1irp9SWSJ5/47P5LnHgqjaqNRewf5PbhigYqHx18tco+/qVqaJeJrvG3QefrApXxVQf72Hv5vsYIc",
	"/jfaKBmtNIw6wUvuENppm/UUutpohx+uMWobo8S0ttqaGq0XGMJQ6Byfhw9+WSPk4LwVeg5tm4HF20ZY",
	"LCF/u144zbqFZvYOCw9tBmvTTww/e+iVKOlvZaziHnIQ2v/0A6wNC+1xjhYy+Odsbs40V/R2Mu75LMqE",
	"u9Mth4P5RE48p//7AnhJa9oMovFe8jKoF8abv54SyDVJJqIJn7cUZ9HRZEGsNbYfGHav+6XuqbhCfyws",
	"XqGfKD7HMbrCitoLoz9cZdAQ9cXH/FigyaDmfvF4B4SUh6WplP8h3Dphbjs84VG5x+C0SdhaNbeWL+n3",
	"yxUceVkKyh2X11txe9tgwp3XWJi5Fv8ejVD+rMtj8F1a2ce6Jg0vAyo+AldUbqErQ6KF0Z4XITxUXEjI",
	"QZufCTPnhVGU33KDZcjhZiEcE475BbJKaC5ZbQ2VglXGsivEvy8tF9qxwjTWURd74SVV7HdeIFsVi5Sx",
	"X64nkMF7tC6qfnF+cX5BFk2NmtcCcvj+/OL8xQqLAVkjQUGMmpCH0Bgm1oZgwkntpIR8O08QoY3OX5py",
	"2YWMOkipRnpRc+tH1ExnJY/4ixnr910lJO503kxobpeb1hummTb2WKxZUPbdxcUDb3hdS1GEKEbvHOVk",
	"25V9pU3hIljcLZ5rigJd1UjK8o9HtB9ZOGGR6yULXMy+IXwoMxMSGdm0vPDfhky5RinKYlc2FmrMjGYO",
	"7ftAZJ7PHRHTG8+rCqYkFZHgRl3N5pjAQYKPA5osV+jRutAzux6H9WwyBuoRyOG2wVDhFY0GatxwZeSk",
	"TZLWyGgGSLnts/L0GYGxb0M6QYCMzZ3egkhljToIJF3jJkHSKe3o4uTg8SlZ7ItHjKPnES/37C6795e9",
	"G8zT40/futrdoxrh6zn3lYGbWqIquFrDFtyxGaJmRZAtP1NcxMiYxjuGm0LuAYSUgwSycyCGZyxH+uR9",
	"gl15hZ5xKVnI7d68l+F2T25tnh7Q9879/zH+7tZ9MTv8wPjjFKk6RHJYO676cOjQ99WiITXLOFF+OAgH",
	"trv8D+/WvfnAV3EjHJ6KnCAc1sEcBoomzFxCsZrkcKB8/uNbeoj0iY9vA8Ong45vMYnlZzspIO/2wqFd",
	"v3vI+q86ODA+M42PVwO34fzVoCwblrsTfrE+vKykouG+1BujkDlvuab7R6MLer9l7WZhhSXGWSaECfm2",
	"FHoerTFekw+6QOaFQin0tt83QqENAg7aaftfAAAA//+J8nD10xkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
