openapi: "3.0.1"
info:
  title: 
  description: This is the final project for GeekBrains course
  version: 1.0.0
  contact:
    email: no@name.com

tags:
- name: Image
  description: Operation about images
- name: Staff
  description: Operation with staff
- name: Thrirparty
  description: Some strange functions
- name: Timerecords
  description: Recording staff apperance timelines

paths:
  /stuff/add:
    post:
      summary: Create new employee
      tags: 
        - Staff
      operationId: CreateEmployee
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/CreateEmployeeRequest"
      responses:
        200:
          description: employee has been created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateEmployeeResponse"
        500:
          description: any error (for mobile contract)
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Error"
  
  

components:
  schemas:
    Any: {}
    CreateEmployeeRequest:
      type: object
      required:
        - name
        - photo_id
        - meta
      properties:
        name:
          type: string
        photo_id:
          type: integer
          format: int64
          x-go-name: PhotoID
        meta:
          $ref: "#/components/schemas/Any"
    CreateEmployeeResponse:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
          x-go-name: ID
    Error:
      type: object
      properties:
        error:
          type: string

